# Generated by Django 4.0.6 on 2022-08-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collex', '0002_collection_slug_item_image_url_item_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_rgb', models.CharField(blank=True, max_length=15, null=True)),
                ('_lab', models.CharField(blank=True, max_length=255, null=True)),
                ('_hex', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['collection', 'token_id']},
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manually_removed', models.BooleanField(default=False)),
                ('manually_added', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collex.color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collex.item')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='colors',
            field=models.ManyToManyField(blank=True, to='collex.color'),
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(blank=True, through='collex.ItemColor', to='collex.color'),
        ),
    ]
