# Generated by Django 4.0.6 on 2022-08-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collex', '0003_color_alter_collection_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='_lab',
        ),
    ]
