# Generated by Django 4.0.6 on 2022-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collex', '0005_itemcolor_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['_hex']},
        ),
        migrations.AlterModelOptions(
            name='itemcolor',
            options={'ordering': ['manually_removed', '-amount']},
        ),
        migrations.AddField(
            model_name='item',
            name='colors_string',
            field=models.TextField(blank=True),
        ),
    ]
