# Generated by Django 4.0.6 on 2022-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collex', '0006_alter_color_options_alter_itemcolor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='colors_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
