# Generated by Django 4.0.6 on 2022-08-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collex', '0007_item_colors_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='color_filters',
            field=models.BooleanField(default=False),
        ),
    ]
