# Generated by Django 4.0.6 on 2022-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collex', '0008_collection_color_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcolor',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
